# Generated by Django 2.1 on 2018-08-29 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank='False', max_length=50)),
                ('phone_number', models.IntegerField(blank='False')),
                ('country', models.CharField(blank='False', max_length=50)),
                ('postcode', models.CharField(blank='False', max_length=50)),
                ('town_or_city', models.CharField(blank='True', max_length=50)),
                ('street_address1', models.CharField(blank='False', max_length=50)),
                ('street_address2', models.CharField(blank='True', max_length=50)),
                ('county', models.CharField(blank='True', max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='checkout.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Product')),
            ],
        ),
    ]
